app:
  port: "3000"

db:
  user: "admin"
  password: "secret"
  host: "postgres"
  port: "5432"
  name: "microservices_db"

kafka:
  brokers: "kafka:9092"
  topic: "user-events"

jwt:
  private_key_path: "./secrets/private.pem"
  public_key_path: "./secrets/public.pem"
