app:
  port: "3001
  
kafka:
  brokers: "kafka:9092"
  topic: "user-events"
  group_id: "email-verification-consumer"

db:
  user: "admin"
  password: "secret"
  host: "postgres"
  port: "5432"
  name: "microservices_db"
